/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as SearchPhotoRouteImport } from './routes/search.photo'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as SearchPhotoCaptureRouteImport } from './routes/search.photo.capture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchPhotoRoute = SearchPhotoRouteImport.update({
  id: '/search/photo',
  path: '/search/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchPhotoCaptureRoute = SearchPhotoCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => SearchPhotoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/coin/$id': typeof CoinIdRoute
  '/search/photo': typeof SearchPhotoRouteWithChildren
  '/search/': typeof SearchIndexRoute
  '/search/photo/capture': typeof SearchPhotoCaptureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/coin/$id': typeof CoinIdRoute
  '/search/photo': typeof SearchPhotoRouteWithChildren
  '/search': typeof SearchIndexRoute
  '/search/photo/capture': typeof SearchPhotoCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/coin/$id': typeof CoinIdRoute
  '/search/photo': typeof SearchPhotoRouteWithChildren
  '/search/': typeof SearchIndexRoute
  '/search/photo/capture': typeof SearchPhotoCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/coin/$id'
    | '/search/photo'
    | '/search/'
    | '/search/photo/capture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/coin/$id'
    | '/search/photo'
    | '/search'
    | '/search/photo/capture'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/coin/$id'
    | '/search/photo'
    | '/search/'
    | '/search/photo/capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CoinIdRoute: typeof CoinIdRoute
  SearchPhotoRoute: typeof SearchPhotoRouteWithChildren
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/photo': {
      id: '/search/photo'
      path: '/search/photo'
      fullPath: '/search/photo'
      preLoaderRoute: typeof SearchPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/photo/capture': {
      id: '/search/photo/capture'
      path: '/capture'
      fullPath: '/search/photo/capture'
      preLoaderRoute: typeof SearchPhotoCaptureRouteImport
      parentRoute: typeof SearchPhotoRoute
    }
  }
}

interface SearchPhotoRouteChildren {
  SearchPhotoCaptureRoute: typeof SearchPhotoCaptureRoute
}

const SearchPhotoRouteChildren: SearchPhotoRouteChildren = {
  SearchPhotoCaptureRoute: SearchPhotoCaptureRoute,
}

const SearchPhotoRouteWithChildren = SearchPhotoRoute._addFileChildren(
  SearchPhotoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CoinIdRoute: CoinIdRoute,
  SearchPhotoRoute: SearchPhotoRouteWithChildren,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
